### ISSUE TITLE
[Bad label in the main paper] We reviewed the paper and noticed that the image representing Indonesian cuisine is very inaccurate.

### ISSUE THREAD

**Issue by gentaiscool** [mbzuai-oryx/ALM-Bench#1]
@afaji and I noticed this issue.

The image representing Indonesian cuisine in the paper is inaccurate. We are curious about your data annotation process, as the image certainly doesn't depict "nasi goreng." 

Kindly select a more accurate example to include in the paper.

We are also interested in understanding your process for selecting annotators, as the example in your main paper is inaccurate. It would be beneficial to choose a more representative example rather than presenting a flawed one. I recommend conducting a second round of quality checks to ensure the data's accuracy and reliability.

<img width="897" alt="image" src="https://github.com/user-attachments/assets/59f8835a-0de4-459c-a263-356f1610aa59">

**Comment by gentaiscool** [comment]
I also mentioned about this issue with @ashmalvayani offline.

**Comment by ashmalvayani** [comment]
This issue has been addressed and the image has been replaced with a better representative image. 

To select the annotators, we contacted our in-house volunteers in our team of collaborated institutes. For the remaining languages, we reached out to various low-resource communities and authors individually for the annotation task.

**Comment by gentaiscool** [comment]
Thank you for addressing the issue. Could you find another one? I think the current picture is not mie goreng. It should be bihun goreng. Mie and bihun are two different things.

<img width="245" alt="image" src="https://github.com/user-attachments/assets/7ef57a19-8449-4a48-82fc-f5cf07c7fe69">

**Comment by gentaiscool** [comment]
Thank you for addressing the issue.

However, the current picture is still not correct. It is bihun goreng not mie goreng. Mie and bihun are two different things. @ashmalvayani 

<img width="245" alt="image" src="https://github.com/user-attachments/assets/06a9aba0-f2c9-4b63-a9c7-13fd721519f4">

**Comment by w11wo** [comment]
Hi. I noticed that while the image has been correctly replaced with a photo of nasi goreng, I still find that the annotation may not be accurate: https://huggingface.co/datasets/MBZUAI/ALM-Bench/viewer/default/test?f%5BLanguage%5D%5Bvalue%5D='Indonesian'&p=1&row=4816

For the question: `True or False. The image shows a traditional Indonesian dish known as Nasi Goreng.`, shouldn't the answer now be `true`/`Benar`?

**Comment by gentaiscool** [comment]
could we revisit this issue?
